name: UHCControlUtils
version: ${project.version}
author: ArmouredMonkey
main: io.github.armouredmonkey.UHCControlUtils
depend: [LuckPerms]
api-version: 1.13

commands:
  reload:
    description: Reloads the UHC Control Utils config
    permission: uhcutils.reload
    usage: reload
  sync:
    description: Refreshes contexts and syncs with DiscordSRV
    permission: uhcutils.sync
    usage: sync
