name: ${project.name}
version: ${project.version}
author: ArmouredMonkey
main: io.github.armouredmonkey.LPTeamSync
depend: [LuckPerms]
api-version: 1.13

commands:
  lpts-reload:
    description: Reloads the LPTeamSync config
    permission: lpteamsync.reload
    usage: /lpts-reload
  lpts-sync:
    description: Refreshes contexts and syncs with DiscordSRV
    permission: lpteamsync.sync
    usage: /lpts-sync
